version: '3.8'

services:

  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment: 
      - CHOKIDAR_USEPOLLING=true
  
  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment: 
      - CHOKIDAR_USEPOLLING=true
      